file = open("output.txt", 'wt')
file.write(input("Enter text to write to the file: ")+"\n")
print("Data successfully written to output.txt.")
file.close()
file = open("output.txt", 'at')
file.write(input("Enter Additional text to append: ")+"\n")
print("Data successfully appended.")
file.close()
print("Final content of output.text:")
file = open("output.txt", 'rt')
print(file.read())
file.close()
